export const EMPLOYEE_ID_PREFIX = "LSTA";

export const employeeRoles = [
  "CEO",
  "CEO_COORDINATOR",
  "SALES_HEAD",
  "AREA_SALES_MANAGER",
  "SHOP_MANAGER",
  "SHOP_ACCOUNTANT",
  "DSA",
  "DSP",
  "BA_COORDINATOR",
  "CLEANING_STAFF",
  "SECURITY_STAFF",
  "EBU_SUPERVISOR",
  "EBU_FTTH_SUPERVISOR",
  "EBU_TECHNICAL_SALES_LEAD",
  "EBU_FTTH_SALES",
  "DISTRIBUTION_MANAGER",
  "DISTRIBUTION_OFFICER",
  "FINANCE_DIRECTOR",
  "TREASURY_MANAGER",
  "ACCOUNTANT",
  "FINANCIAL_CONTROL_REPORTING_MANAGER",
  "HR_MANAGER",
  "HR_OFFICER",
  "TECHNOLOGY_MANAGER",
  "EMPLOYEE",
  "OTHER"
] as const;

export type EmployeeRoleValue = (typeof employeeRoles)[number];

export const employmentTypes = [
  "FULL_TIME",
  "PART_TIME",
  "COMMISSION_BASED",
  "CONTRACT",
  "INTERN",
  "TEMPORARY",
  "OTHER"
] as const;

export type EmploymentTypeValue = (typeof employmentTypes)[number];

export const employmentStatuses = [
  "DRAFT",
  "ONBOARDING",
  "ACTIVE",
  "ON_PROBATION",
  "SUSPENDED",
  "ON_LEAVE",
  "TRANSFERRED",
  "RESIGNED",
  "TERMINATED",
  "EXITED"
] as const;

export type EmploymentStatusValue = (typeof employmentStatuses)[number];

export const systemRoles = [
  "SUPER_ADMIN",
  "CEO",
  "CEO_COORDINATOR",
  "HR_ADMIN",
  "HR_MANAGER",
  "HR_OFFICER",
  "FINANCE_DIRECTOR",
  "FINANCE_PAYROLL",
  "TREASURY_MANAGER",
  "FINANCIAL_CONTROL_REPORTING_MANAGER",
  "DISTRIBUTION_MANAGER",
  "DISTRIBUTION_OFFICER",
  "TECHNOLOGY_MANAGER",
  "SALES_HEAD",
  "AREA_SALES_MANAGER",
  "SHOP_MANAGER",
  "EMPLOYEE",
  "AUDITOR"
] as const;

export type SystemRoleValue = (typeof systemRoles)[number];

export const permissionKeys = [
  "employee.view",
  "employee.create",
  "employee.update",
  "employee.delete",
  "salary.view",
  "salary.update",
  "assignment.update",
  "import.view",
  "import.validate",
  "import.approve",
  "document.upload",
  "document.view",
  "document.view_sensitive",
  "document.deactivate",
  "required_document_rule.view",
  "required_document_rule.manage",
  "achievement.create",
  "achievement.view",
  "achievement.update",
  "achievement.approve",
  "evaluation.create",
  "evaluation.view",
  "evaluation.update",
  "evaluation.submit",
  "evaluation.review",
  "evaluation.approve",
  "evaluation.configure",
  "evaluation.view_all",
  "leave.view",
  "leave.create",
  "leave.update",
  "leave.approve",
  "status.update",
  "onboarding.view",
  "onboarding.update",
  "termination.initiate",
  "termination.approve",
  "disciplinary.view",
  "disciplinary.create",
  "disciplinary.update",
  "disciplinary.submit",
  "disciplinary.review",
  "disciplinary.approve",
  "disciplinary.close",
  "termination.view",
  "termination.create",
  "termination.update",
  "termination.submit",
  "termination.review",
  "termination.approve",
  "termination.complete_exit",
  "termination.update_final_payment",
  "transfer.view",
  "transfer.create",
  "transfer.update",
  "transfer.submit",
  "transfer.approve",
  "transfer.complete",
  "promotion.view",
  "promotion.create",
  "promotion.update",
  "promotion.submit",
  "promotion.approve",
  "promotion.complete",
  "approval.view",
  "approval.configure",
  "approval.act",
  "notification.view",
  "notification.manage",
  "export.create",
  "self_service.view",
  "payroll_preparation.view",
  "payroll_preparation.create",
  "payroll_preparation.validate",
  "payroll_preparation.approve",
  "payroll_preparation.export",
  "kpi.view",
  "kpi.create",
  "kpi.update",
  "kpi.import",
  "kpi.approve",
  "analytics.view",
  "compliance.view",
  "notification_preferences.manage",
  "self_service.profile_update_request",
  "profile_change_request.view",
  "profile_change_request.approve",
  "approval_governance.configure",
  "data_quality.view",
  "data_quality.assign",
  "data_quality.resolve",
  "reminder.view",
  "reminder.create",
  "reminder.complete",
  "system_settings.view",
  "system_settings.update",
  "export_history.view",
  "salary_review.view",
  "salary_review.create",
  "salary_review.update",
  "salary_review.review",
  "salary_review.approve",
  "salary_review.complete",
  "payroll_rule.view",
  "payroll_rule.create",
  "payroll_rule.update",
  "payroll_rule.deactivate",
  "paye_tax.view",
  "paye_tax.manage",
  "pension_rule.view",
  "pension_rule.manage",
  "payroll_attendance.view",
  "payroll_attendance.create",
  "payroll_attendance.approve",
  "payroll_allowance.view",
  "payroll_allowance.create",
  "payroll_allowance.approve",
  "payroll_deduction.view",
  "payroll_deduction.create",
  "payroll_deduction.approve",
  "commission_plan.view",
  "commission_plan.create",
  "commission_plan.update",
  "commission_plan.approve",
  "commission_calculation.view",
  "commission_calculation.create",
  "commission_calculation.update",
  "commission_calculation.review",
  "commission_calculation.approve",
  "commission_calculation.export",
  "payroll_calculation.view",
  "payroll_calculation.run",
  "payroll_validation.view",
  "payroll_validation.resolve",
  "compensation_dashboard.view",
  "reports.view",
  "audit.view",
  "user.manage",
  "role.manage",
  "payroll_export_template.view",
  "payroll_export_template.create",
  "payroll_export_template.update",
  "payroll_lock.view",
  "payroll_lock.manage",
  "payroll_adjustment.view",
  "payroll_adjustment.create",
  "payroll_adjustment.approve",
  "attendance.view",
  "attendance.create",
  "attendance.import",
  "attendance.approve",
  "leave_policy.view",
  "leave_policy.manage",
  "leave_balance.view",
  "leave_balance.adjust",
  "kpi_import_template.view",
  "kpi_import_template.manage",
  "kpi_evaluation_linkage.manage",
  "self_service.leave_request",
  "self_service.resignation_request",
  "manager_dashboard.view",
  "team_attendance.view",
  "team_leave.view",
  "email_template.view",
  "email_template.manage",
  "email_log.view",
  "security_settings.view",
  "security_settings.manage",
  "security_reports.view",
  "data_retention.view",
  "data_retention.manage",
  "integration_token.view",
  "integration_token.manage",
  "integration_event.view",
  "production_readiness.view",
  "system_health.view"
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const disciplinaryIncidentTypes = [
  "ATTENDANCE_ISSUE",
  "PERFORMANCE_ISSUE",
  "MISCONDUCT",
  "POLICY_VIOLATION",
  "CUSTOMER_COMPLAINT",
  "CASH_OR_FINANCE_ISSUE",
  "INSUBORDINATION",
  "NEGLIGENCE",
  "OTHER"
] as const;

export const warningLevels = [
  "VERBAL_WARNING",
  "FIRST_WRITTEN_WARNING",
  "SECOND_WRITTEN_WARNING",
  "FINAL_WARNING",
  "SUSPENSION_RECOMMENDATION",
  "TERMINATION_RECOMMENDATION",
  "OTHER"
] as const;

export const roleAliases: Record<string, EmployeeRoleValue> = {
  ceo: "CEO",
  "chief executive officer": "CEO",
  "ceo coordinator": "CEO_COORDINATOR",
  coordinator: "CEO_COORDINATOR",
  "sales head": "SALES_HEAD",
  "head of sales": "SALES_HEAD",
  "area sales manager": "AREA_SALES_MANAGER",
  asm: "AREA_SALES_MANAGER",
  "shop manager": "SHOP_MANAGER",
  sm: "SHOP_MANAGER",
  "shop accountant": "SHOP_ACCOUNTANT",
  "shop-accountant": "SHOP_ACCOUNTANT",
  dsa: "DSA",
  dsp: "DSP",
  "ba coordinator": "BA_COORDINATOR",
  cleaner: "CLEANING_STAFF",
  "cleaning staff": "CLEANING_STAFF",
  security: "SECURITY_STAFF",
  "security staff": "SECURITY_STAFF",
  "ebu supervisor": "EBU_SUPERVISOR",
  "ebu ftth supervisor": "EBU_FTTH_SUPERVISOR",
  "ebu technical sales lead": "EBU_TECHNICAL_SALES_LEAD",
  "ebu ftth sales": "EBU_FTTH_SALES",
  "distribution manager": "DISTRIBUTION_MANAGER",
  "distribution officer": "DISTRIBUTION_OFFICER",
  "finance director": "FINANCE_DIRECTOR",
  "treasury manager": "TREASURY_MANAGER",
  accountant: "ACCOUNTANT",
  accountants: "ACCOUNTANT",
  "financial control and reporting manager": "FINANCIAL_CONTROL_REPORTING_MANAGER",
  "financial control reporting manager": "FINANCIAL_CONTROL_REPORTING_MANAGER",
  "hr manager": "HR_MANAGER",
  "human resources manager": "HR_MANAGER",
  "hr officer": "HR_OFFICER",
  "technology manager": "TECHNOLOGY_MANAGER",
  employee: "EMPLOYEE"
};

export const employmentTypeAliases: Record<string, EmploymentTypeValue> = {
  "full time": "FULL_TIME",
  fulltime: "FULL_TIME",
  permanent: "FULL_TIME",
  "part time": "PART_TIME",
  parttime: "PART_TIME",
  "commission based": "COMMISSION_BASED",
  commission: "COMMISSION_BASED",
  contract: "CONTRACT",
  contractor: "CONTRACT",
  intern: "INTERN",
  internship: "INTERN",
  temporary: "TEMPORARY",
  temp: "TEMPORARY",
  other: "OTHER"
};

export const statusAliases: Record<string, EmploymentStatusValue> = {
  draft: "DRAFT",
  onboarding: "ONBOARDING",
  active: "ACTIVE",
  probation: "ON_PROBATION",
  "on probation": "ON_PROBATION",
  suspended: "SUSPENDED",
  "on leave": "ON_LEAVE",
  leave: "ON_LEAVE",
  transferred: "TRANSFERRED",
  resigned: "RESIGNED",
  terminated: "TERMINATED",
  exited: "EXITED"
};

export const defaultLevelByRole: Partial<Record<EmployeeRoleValue, string>> = {
  DSA: "JUNIOR",
  DSP: "JUNIOR",
  EBU_FTTH_SALES: "JUNIOR"
};

export const headOfficeRoles = new Set<EmployeeRoleValue>([
  "CEO",
  "CEO_COORDINATOR",
  "DISTRIBUTION_MANAGER",
  "DISTRIBUTION_OFFICER",
  "FINANCE_DIRECTOR",
  "TREASURY_MANAGER",
  "ACCOUNTANT",
  "FINANCIAL_CONTROL_REPORTING_MANAGER",
  "HR_MANAGER",
  "HR_OFFICER",
  "TECHNOLOGY_MANAGER"
]);

export const shopBasedRoles = new Set<EmployeeRoleValue>([
  "SHOP_MANAGER",
  "SHOP_ACCOUNTANT",
  "DSA",
  "DSP",
  "BA_COORDINATOR",
  "CLEANING_STAFF",
  "SECURITY_STAFF",
  "EBU_SUPERVISOR",
  "EBU_FTTH_SUPERVISOR",
  "EBU_TECHNICAL_SALES_LEAD",
  "EBU_FTTH_SALES"
]);

export const clusterRequiredRoles = new Set<EmployeeRoleValue>([
  "DSA",
  "DSP"
]);

export const managerRequiredRoles = new Set<EmployeeRoleValue>(
  employeeRoles.filter((role) => role !== "CEO" && role !== "OTHER")
);

export const evaluatorRequiredRoles = new Set<EmployeeRoleValue>([
  "AREA_SALES_MANAGER",
  "SHOP_MANAGER",
  "SHOP_ACCOUNTANT",
  "DSA",
  "DSP",
  "BA_COORDINATOR",
  "CLEANING_STAFF",
  "SECURITY_STAFF",
  "EBU_SUPERVISOR",
  "EBU_FTTH_SUPERVISOR",
  "EBU_TECHNICAL_SALES_LEAD",
  "EBU_FTTH_SALES",
  "DISTRIBUTION_OFFICER",
  "ACCOUNTANT",
  "HR_OFFICER"
]);

export const terminalStatuses = new Set<EmploymentStatusValue>([
  "RESIGNED",
  "TERMINATED",
  "EXITED"
]);

export const allowedStatusTransitions: Record<EmploymentStatusValue, EmploymentStatusValue[]> = {
  DRAFT: ["ONBOARDING", "ACTIVE", "ON_PROBATION", "TERMINATED"],
  ONBOARDING: ["ACTIVE", "ON_PROBATION", "TERMINATED"],
  ACTIVE: ["ON_PROBATION", "SUSPENDED", "ON_LEAVE", "TRANSFERRED", "RESIGNED", "TERMINATED"],
  ON_PROBATION: ["ACTIVE", "SUSPENDED", "RESIGNED", "TERMINATED"],
  SUSPENDED: ["ACTIVE", "TERMINATED", "RESIGNED"],
  ON_LEAVE: ["ACTIVE", "RESIGNED", "TERMINATED"],
  TRANSFERRED: ["ACTIVE", "ON_PROBATION", "RESIGNED", "TERMINATED"],
  RESIGNED: ["EXITED"],
  TERMINATED: ["EXITED"],
  EXITED: []
};

const phase3AdminPermissions: PermissionKey[] = [
  "disciplinary.view",
  "disciplinary.create",
  "disciplinary.update",
  "disciplinary.submit",
  "disciplinary.review",
  "disciplinary.approve",
  "disciplinary.close",
  "termination.view",
  "termination.create",
  "termination.update",
  "termination.submit",
  "termination.review",
  "termination.approve",
  "termination.complete_exit",
  "termination.update_final_payment",
  "transfer.view",
  "transfer.create",
  "transfer.update",
  "transfer.submit",
  "transfer.approve",
  "transfer.complete",
  "promotion.view",
  "promotion.create",
  "promotion.update",
  "promotion.submit",
  "promotion.approve",
  "promotion.complete",
  "approval.view",
  "approval.configure",
  "approval.act",
  "notification.view",
  "notification.manage",
  "export.create",
  "self_service.view"
];

const phase3ManagerPermissions: PermissionKey[] = [
  "disciplinary.view",
  "disciplinary.create",
  "disciplinary.update",
  "disciplinary.submit",
  "disciplinary.review",
  "disciplinary.approve",
  "disciplinary.close",
  "termination.view",
  "termination.create",
  "termination.update",
  "termination.submit",
  "termination.review",
  "termination.approve",
  "transfer.view",
  "transfer.create",
  "transfer.update",
  "transfer.submit",
  "transfer.approve",
  "transfer.complete",
  "promotion.view",
  "promotion.create",
  "promotion.update",
  "promotion.submit",
  "promotion.approve",
  "promotion.complete",
  "approval.view",
  "approval.act",
  "notification.view",
  "export.create",
  "self_service.view"
];

const phase3PreparatoryPermissions: PermissionKey[] = [
  "disciplinary.view",
  "disciplinary.create",
  "disciplinary.update",
  "disciplinary.submit",
  "termination.view",
  "termination.create",
  "termination.update",
  "termination.submit",
  "transfer.view",
  "transfer.create",
  "transfer.update",
  "transfer.submit",
  "promotion.view",
  "promotion.create",
  "promotion.update",
  "promotion.submit",
  "approval.view",
  "notification.view",
  "export.create",
  "self_service.view"
];

const phase3ScopedRequesterPermissions: PermissionKey[] = [
  "disciplinary.view",
  "disciplinary.create",
  "disciplinary.submit",
  "transfer.view",
  "transfer.create",
  "transfer.submit",
  "promotion.view",
  "promotion.create",
  "promotion.submit",
  "approval.view",
  "notification.view",
  "self_service.view"
];

const phase3FinancePermissions: PermissionKey[] = [
  "termination.view",
  "termination.update_final_payment",
  "promotion.view",
  "notification.view",
  "reports.view"
];

const phase3ReadOnlyPermissions: PermissionKey[] = [
  "disciplinary.view",
  "termination.view",
  "transfer.view",
  "promotion.view",
  "approval.view",
  "notification.view",
  "export.create"
];

const phase4AdminPermissions: PermissionKey[] = [
  "payroll_preparation.view",
  "payroll_preparation.create",
  "payroll_preparation.validate",
  "payroll_preparation.approve",
  "payroll_preparation.export",
  "kpi.view",
  "kpi.create",
  "kpi.update",
  "kpi.import",
  "kpi.approve",
  "analytics.view",
  "compliance.view",
  "notification_preferences.manage",
  "self_service.profile_update_request",
  "profile_change_request.view",
  "profile_change_request.approve",
  "approval_governance.configure",
  "data_quality.view",
  "data_quality.assign",
  "data_quality.resolve",
  "required_document_rule.view",
  "required_document_rule.manage",
  "reminder.view",
  "reminder.create",
  "reminder.complete",
  "system_settings.view",
  "system_settings.update",
  "export_history.view"
];

const phase4FinancePermissions: PermissionKey[] = [
  "payroll_preparation.view",
  "payroll_preparation.approve",
  "payroll_preparation.export",
  "analytics.view",
  "compliance.view",
  "notification_preferences.manage",
  "reminder.view",
  "export_history.view"
];

const phase4ManagerPermissions: PermissionKey[] = [
  "kpi.view",
  "kpi.import",
  "analytics.view",
  "compliance.view",
  "notification_preferences.manage",
  "data_quality.view",
  "data_quality.assign",
  "required_document_rule.view",
  "reminder.view",
  "reminder.create",
  "self_service.profile_update_request"
];

const phase4EmployeePermissions: PermissionKey[] = [
  "kpi.view",
  "notification_preferences.manage",
  "self_service.profile_update_request"
];

const phase4ReadOnlyPermissions: PermissionKey[] = [
  "kpi.view",
  "analytics.view",
  "compliance.view",
  "data_quality.view",
  "required_document_rule.view",
  "reminder.view",
  "export_history.view"
];

const phase45AdminPermissions: PermissionKey[] = [
  "salary_review.view",
  "salary_review.create",
  "salary_review.update",
  "salary_review.review",
  "salary_review.approve",
  "salary_review.complete",
  "payroll_rule.view",
  "payroll_rule.create",
  "payroll_rule.update",
  "payroll_rule.deactivate",
  "paye_tax.view",
  "paye_tax.manage",
  "pension_rule.view",
  "pension_rule.manage",
  "payroll_attendance.view",
  "payroll_attendance.create",
  "payroll_attendance.approve",
  "payroll_allowance.view",
  "payroll_allowance.create",
  "payroll_allowance.approve",
  "payroll_deduction.view",
  "payroll_deduction.create",
  "payroll_deduction.approve",
  "commission_plan.view",
  "commission_plan.create",
  "commission_plan.update",
  "commission_plan.approve",
  "commission_calculation.view",
  "commission_calculation.create",
  "commission_calculation.update",
  "commission_calculation.review",
  "commission_calculation.approve",
  "commission_calculation.export",
  "payroll_calculation.view",
  "payroll_calculation.run",
  "payroll_validation.view",
  "payroll_validation.resolve",
  "compensation_dashboard.view"
];

const phase45FinancePermissions: PermissionKey[] = [
  "salary_review.view",
  "salary_review.review",
  "salary_review.approve",
  "payroll_rule.view",
  "payroll_rule.create",
  "payroll_rule.update",
  "paye_tax.view",
  "paye_tax.manage",
  "pension_rule.view",
  "pension_rule.manage",
  "payroll_attendance.view",
  "payroll_attendance.create",
  "payroll_attendance.approve",
  "payroll_allowance.view",
  "payroll_allowance.create",
  "payroll_allowance.approve",
  "payroll_deduction.view",
  "payroll_deduction.create",
  "payroll_deduction.approve",
  "commission_plan.view",
  "commission_plan.create",
  "commission_plan.update",
  "commission_plan.approve",
  "commission_calculation.view",
  "commission_calculation.create",
  "commission_calculation.update",
  "commission_calculation.review",
  "commission_calculation.approve",
  "commission_calculation.export",
  "payroll_calculation.view",
  "payroll_calculation.run",
  "payroll_validation.view",
  "payroll_validation.resolve",
  "compensation_dashboard.view"
];

const phase45PayrollViewPermissions: PermissionKey[] = [
  "salary_review.view",
  "payroll_rule.view",
  "paye_tax.view",
  "pension_rule.view",
  "payroll_attendance.view",
  "payroll_allowance.view",
  "payroll_deduction.view",
  "commission_plan.view",
  "commission_calculation.view",
  "commission_calculation.export",
  "payroll_calculation.view",
  "payroll_calculation.run",
  "payroll_validation.view",
  "compensation_dashboard.view"
];

const phase45ManagerRequestPermissions: PermissionKey[] = [
  "salary_review.view",
  "salary_review.create",
  "commission_calculation.view",
  "commission_calculation.create",
  "compensation_dashboard.view"
];

const phase45ReadOnlyPermissions: PermissionKey[] = [
  "salary_review.view",
  "payroll_rule.view",
  "paye_tax.view",
  "pension_rule.view",
  "payroll_attendance.view",
  "payroll_allowance.view",
  "payroll_deduction.view",
  "commission_plan.view",
  "commission_calculation.view",
  "payroll_calculation.view",
  "payroll_validation.view",
  "compensation_dashboard.view"
];

const phase5PayrollAdminPermissions: PermissionKey[] = [
  "payroll_export_template.view",
  "payroll_export_template.create",
  "payroll_export_template.update",
  "payroll_lock.view",
  "payroll_lock.manage",
  "payroll_adjustment.view",
  "payroll_adjustment.create",
  "payroll_adjustment.approve"
];

const phase5HrAdminPermissions: PermissionKey[] = [
  ...phase5PayrollAdminPermissions,
  "attendance.view",
  "attendance.create",
  "attendance.import",
  "attendance.approve",
  "leave_policy.view",
  "leave_policy.manage",
  "leave_balance.view",
  "leave_balance.adjust",
  "kpi_import_template.view",
  "kpi_import_template.manage",
  "kpi_evaluation_linkage.manage",
  "manager_dashboard.view",
  "team_attendance.view",
  "team_leave.view",
  "email_template.view",
  "email_template.manage",
  "email_log.view",
  "security_reports.view",
  "data_retention.view",
  "data_retention.manage",
  "production_readiness.view",
  "system_health.view"
];

const phase5FinancePermissions: PermissionKey[] = [
  ...phase5PayrollAdminPermissions,
  "attendance.view",
  "leave_balance.view",
  "email_log.view",
  "security_reports.view",
  "production_readiness.view",
  "system_health.view"
];

const phase5ManagerPermissions: PermissionKey[] = [
  "attendance.view",
  "attendance.create",
  "attendance.import",
  "attendance.approve",
  "leave_balance.view",
  "manager_dashboard.view",
  "team_attendance.view",
  "team_leave.view",
  "self_service.leave_request"
];

const phase5EmployeePermissions: PermissionKey[] = [
  "leave_balance.view",
  "self_service.leave_request",
  "self_service.resignation_request"
];

const phase5SuperAdminPermissions: PermissionKey[] = [
  "security_settings.view",
  "security_settings.manage",
  "integration_token.view",
  "integration_token.manage",
  "integration_event.view"
];

export const rolePermissions: Record<SystemRoleValue, PermissionKey[]> = {
  SUPER_ADMIN: [...permissionKeys],
  CEO: [
    "employee.view",
    "evaluation.create",
    "evaluation.view",
    "evaluation.approve",
    "disciplinary.view",
    "disciplinary.approve",
    "termination.view",
    "termination.approve",
    "transfer.view",
    "transfer.approve",
    "promotion.view",
    "promotion.approve",
    "approval.view",
    "approval.act",
    "notification.view",
    "export.create",
    "analytics.view",
    "compliance.view",
    "export_history.view",
    "salary_review.view",
    "commission_calculation.view",
    "compensation_dashboard.view",
    "reports.view",
    "audit.view",
    "achievement.approve"
  ],
  CEO_COORDINATOR: ["employee.view", "reports.view", "evaluation.view"],
  HR_ADMIN: [
    "employee.view",
    "employee.create",
    "employee.update",
    "salary.view",
    "salary.update",
    "assignment.update",
    "onboarding.view",
    "onboarding.update",
    "import.view",
    "import.validate",
    "import.approve",
    "document.upload",
    "document.view",
    "document.view_sensitive",
    "document.deactivate",
    "achievement.create",
    "achievement.view",
    "achievement.update",
    "achievement.approve",
    "evaluation.create",
    "evaluation.view",
    "evaluation.update",
    "evaluation.submit",
    "evaluation.review",
    "evaluation.approve",
    "evaluation.configure",
    "evaluation.view_all",
    "leave.view",
    "leave.create",
    "leave.update",
    "leave.approve",
    "status.update",
    "termination.initiate",
    "termination.approve",
    ...phase3AdminPermissions,
    ...phase4AdminPermissions,
    ...phase45AdminPermissions,
    ...phase5HrAdminPermissions,
    ...phase5SuperAdminPermissions,
    "reports.view",
    "audit.view",
    "user.manage",
    "role.manage"
  ],
  HR_MANAGER: [
    "employee.view",
    "employee.create",
    "employee.update",
    "assignment.update",
    "onboarding.view",
    "onboarding.update",
    "document.upload",
    "document.view",
    "document.view_sensitive",
    "document.deactivate",
    "achievement.create",
    "achievement.view",
    "achievement.update",
    "achievement.approve",
    "evaluation.create",
    "evaluation.view",
    "evaluation.update",
    "evaluation.submit",
    "evaluation.review",
    "evaluation.approve",
    "evaluation.view_all",
    "status.update",
    "termination.initiate",
    "termination.approve",
    ...phase3ManagerPermissions,
    ...phase4ManagerPermissions,
    ...phase45ManagerRequestPermissions,
    ...phase5HrAdminPermissions,
    "reports.view",
    "audit.view",
    "import.view",
    "import.validate",
    "leave.view",
    "leave.create",
    "leave.update",
    "leave.approve"
  ],
  HR_OFFICER: [
    "employee.view",
    "employee.create",
    "employee.update",
    "assignment.update",
    "document.upload",
    "document.view",
    "onboarding.view",
    "onboarding.update",
    "achievement.create",
    "achievement.view",
    "achievement.update",
    "evaluation.create",
    "evaluation.view",
    "evaluation.update",
    "evaluation.submit",
    "status.update",
    ...phase3PreparatoryPermissions,
    "salary_review.view",
    "salary_review.create",
    "payroll_attendance.view",
    "payroll_attendance.create",
    "payroll_allowance.view",
    "payroll_allowance.create",
    "payroll_deduction.view",
    "payroll_deduction.create",
    "commission_plan.view",
    "commission_calculation.view",
    "commission_calculation.create",
    "payroll_validation.view",
    "compensation_dashboard.view",
    "attendance.view",
    "attendance.create",
    "attendance.import",
    "attendance.approve",
    "leave_policy.view",
    "leave_balance.view",
    "leave_balance.adjust",
    "kpi_import_template.view",
    "manager_dashboard.view",
    "team_attendance.view",
    "team_leave.view",
    "production_readiness.view",
    "system_health.view",
    "kpi.view",
    "kpi.import",
    "analytics.view",
    "compliance.view",
    "notification_preferences.manage",
    "profile_change_request.view",
    "data_quality.view",
    "data_quality.assign",
    "reminder.view",
    "reminder.create",
    "reports.view",
    "import.view",
    "import.validate",
    "leave.view",
    "leave.create",
    "leave.update"
  ],
  FINANCE_DIRECTOR: [
    "employee.view",
    "salary.view",
    "document.view",
    "evaluation.create",
    "evaluation.view",
    "evaluation.update",
    "evaluation.submit",
    "evaluation.approve",
    ...phase3FinancePermissions,
    ...phase4FinancePermissions,
    ...phase45FinancePermissions,
    ...phase5FinancePermissions,
    "reports.view"
  ],
  FINANCE_PAYROLL: [
    "employee.view",
    "salary.view",
    "document.view",
    ...phase3FinancePermissions,
    ...phase4FinancePermissions,
    ...phase45PayrollViewPermissions,
    ...phase5FinancePermissions
  ],
  TREASURY_MANAGER: ["employee.view", "evaluation.create", "evaluation.view", "evaluation.submit", "reports.view"],
  FINANCIAL_CONTROL_REPORTING_MANAGER: [
    "employee.view",
    "evaluation.create",
    "evaluation.view",
    "evaluation.submit",
    "reports.view"
  ],
  DISTRIBUTION_MANAGER: [
    "employee.view",
    "evaluation.create",
    "evaluation.view",
    "evaluation.submit",
    ...phase4ManagerPermissions,
    ...phase45ManagerRequestPermissions,
    ...phase3ScopedRequesterPermissions,
    ...phase5ManagerPermissions,
    "reports.view"
  ],
  DISTRIBUTION_OFFICER: ["employee.view", "reports.view"],
  TECHNOLOGY_MANAGER: ["employee.view", "evaluation.create", "evaluation.view", "evaluation.submit", "reports.view"],
  SALES_HEAD: [
    "employee.view",
    "achievement.create",
    "achievement.view",
    ...phase4ManagerPermissions,
    ...phase45ManagerRequestPermissions,
    ...phase3ScopedRequesterPermissions,
    ...phase5ManagerPermissions,
    "evaluation.create",
    "evaluation.view",
    "evaluation.submit",
    "evaluation.approve",
    "reports.view"
  ],
  AREA_SALES_MANAGER: [
    "employee.view",
    "achievement.create",
    "achievement.view",
    ...phase4ManagerPermissions,
    ...phase45ManagerRequestPermissions,
    ...phase3ScopedRequesterPermissions,
    ...phase5ManagerPermissions,
    "evaluation.create",
    "evaluation.view",
    "evaluation.submit",
    "leave.view",
    "reports.view"
  ],
  SHOP_MANAGER: [
    "employee.view",
    "document.view",
    "achievement.create",
    "achievement.view",
    ...phase4ManagerPermissions,
    ...phase45ManagerRequestPermissions,
    ...phase3ScopedRequesterPermissions,
    ...phase5ManagerPermissions,
    "evaluation.create",
    "evaluation.view",
    "evaluation.submit",
    "leave.view"
  ],
  EMPLOYEE: [
    "employee.view",
    "document.view",
    "achievement.view",
    "leave.view",
    "termination.view",
    "notification.view",
    "self_service.view",
    ...phase4EmployeePermissions,
    ...phase5EmployeePermissions
  ],
  AUDITOR: [
    "employee.view",
    "import.view",
    "document.view",
    "achievement.view",
    "evaluation.view",
    "leave.view",
    ...phase3ReadOnlyPermissions,
    ...phase4ReadOnlyPermissions,
    ...phase45ReadOnlyPermissions,
    "payroll_lock.view",
    "payroll_adjustment.view",
    "attendance.view",
    "leave_policy.view",
    "leave_balance.view",
    "kpi_import_template.view",
    "email_log.view",
    "security_reports.view",
    "data_retention.view",
    "integration_event.view",
    "production_readiness.view",
    "system_health.view",
    "reports.view",
    "audit.view"
  ]
};

export const onboardingItems = [
  ["id_collected", "ID collected"],
  ["contract_signed", "Contract signed"],
  ["emergency_contact_added", "Emergency contact added"],
  ["bank_payment_details_collected", "Bank/payment details collected"],
  ["employment_type_confirmed", "Employment type confirmed"],
  ["role_assigned", "Role assigned"],
  ["manager_assigned", "Manager assigned"],
  ["department_division_assigned", "Department/division assigned"],
  ["shop_region_assigned", "Shop/region assigned if applicable"],
  ["salary_confirmed", "Salary confirmed"],
  ["start_date_confirmed", "Start date confirmed"],
  ["documents_uploaded", "Documents uploaded"]
] as const;

export const exitItems = [
  ["letter_uploaded", "Resignation or termination letter uploaded"],
  ["property_returned", "Company property returned"],
  ["sim_returned", "SIM returned if applicable"],
  ["device_returned", "Device returned if applicable"],
  ["id_card_returned", "ID card returned if applicable"],
  ["final_salary_reviewed", "Final salary reviewed"],
  ["outstanding_balance_checked", "Outstanding balance checked"],
  ["clearance_approved", "Clearance approved"],
  ["exit_interview_completed", "Exit interview completed"],
  ["system_access_removed", "System access removed"],
  ["final_status_updated", "Final employee status updated"]
] as const;
