ALTER TYPE "DocumentVisibility" ADD VALUE IF NOT EXISTS 'PUBLIC_TO_HR';
ALTER TYPE "DocumentVisibility" ADD VALUE IF NOT EXISTS 'MANAGER_VISIBLE';
ALTER TYPE "DocumentVisibility" ADD VALUE IF NOT EXISTS 'EMPLOYEE_VISIBLE';
ALTER TYPE "DocumentVisibility" ADD VALUE IF NOT EXISTS 'SENSITIVE_HR_ONLY';
ALTER TYPE "DocumentVisibility" ADD VALUE IF NOT EXISTS 'SALARY_RESTRICTED';

ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'ANNUAL_LEAVE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'SICK_LEAVE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'MATERNITY_LEAVE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'PATERNITY_LEAVE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'UNPAID_LEAVE';
ALTER TYPE "LeaveType" ADD VALUE IF NOT EXISTS 'EMERGENCY_LEAVE';

ALTER TYPE "ApprovalStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';

ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_UPLOAD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'IMPORT_VALIDATION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EMPLOYEE_IMPORT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCUMENT_DOWNLOAD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCUMENT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOCUMENT_DEACTIVATION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_APPROVAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_REJECTION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LEAVE_CANCELLATION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT_SUBMISSION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ACHIEVEMENT_REJECTION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVALUATION_CREATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVALUATION_UPDATE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVALUATION_REVIEW';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVALUATION_REJECTION';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'EVALUATION_CRITERIA_CHANGE';

ALTER TABLE "EmployeeDocument"
  ADD COLUMN IF NOT EXISTS "originalFilename" TEXT,
  ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Achievement"
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "LeaveRecord"
  ADD COLUMN IF NOT EXISTS "totalDays" DECIMAL(6,2),
  ADD COLUMN IF NOT EXISTS "requestedById" TEXT,
  ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "ImportBatch"
  ADD COLUMN IF NOT EXISTS "uploadedFile" TEXT,
  ADD COLUMN IF NOT EXISTS "validRows" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "approvedById" TEXT,
  ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "notes" TEXT;

ALTER TABLE "ImportRow"
  ADD COLUMN IF NOT EXISTS "employeeCreated" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "employeeUpdated" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "notes" TEXT;

ALTER TABLE "EvaluationCriteria"
  ADD COLUMN IF NOT EXISTS "createdById" TEXT;

CREATE TABLE IF NOT EXISTS "EvaluationScoreItem" (
  "id" TEXT NOT NULL,
  "evaluationId" TEXT NOT NULL,
  "criteriaId" TEXT NOT NULL,
  "departmentId" TEXT,
  "score" DECIMAL(6,2) NOT NULL,
  "comments" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "EvaluationScoreItem_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "EvaluationScoreItem_evaluationId_criteriaId_key"
  ON "EvaluationScoreItem"("evaluationId", "criteriaId");
CREATE INDEX IF NOT EXISTS "EvaluationScoreItem_criteriaId_idx" ON "EvaluationScoreItem"("criteriaId");

ALTER TABLE "EvaluationScoreItem"
  ADD CONSTRAINT "EvaluationScoreItem_evaluationId_fkey"
  FOREIGN KEY ("evaluationId") REFERENCES "EmployeeEvaluation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "EvaluationScoreItem"
  ADD CONSTRAINT "EvaluationScoreItem_criteriaId_fkey"
  FOREIGN KEY ("criteriaId") REFERENCES "EvaluationCriteria"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "EvaluationScoreItem"
  ADD CONSTRAINT "EvaluationScoreItem_departmentId_fkey"
  FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "ImportFieldMapping" (
  "id" TEXT NOT NULL,
  "importBatchId" TEXT NOT NULL,
  "sourceColumn" TEXT NOT NULL,
  "targetField" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ImportFieldMapping_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "ImportFieldMapping_importBatchId_sourceColumn_key"
  ON "ImportFieldMapping"("importBatchId", "sourceColumn");
CREATE INDEX IF NOT EXISTS "ImportFieldMapping_targetField_idx" ON "ImportFieldMapping"("targetField");

ALTER TABLE "ImportFieldMapping"
  ADD CONSTRAINT "ImportFieldMapping_importBatchId_fkey"
  FOREIGN KEY ("importBatchId") REFERENCES "ImportBatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS "ImportValidationIssue" (
  "id" TEXT NOT NULL,
  "importBatchId" TEXT NOT NULL,
  "importRowId" TEXT,
  "severity" TEXT NOT NULL,
  "fieldName" TEXT NOT NULL,
  "issueCode" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "suggestedFix" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ImportValidationIssue_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ImportValidationIssue_importBatchId_severity_idx"
  ON "ImportValidationIssue"("importBatchId", "severity");
CREATE INDEX IF NOT EXISTS "ImportValidationIssue_fieldName_idx" ON "ImportValidationIssue"("fieldName");

ALTER TABLE "ImportValidationIssue"
  ADD CONSTRAINT "ImportValidationIssue_importBatchId_fkey"
  FOREIGN KEY ("importBatchId") REFERENCES "ImportBatch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ImportValidationIssue"
  ADD CONSTRAINT "ImportValidationIssue_importRowId_fkey"
  FOREIGN KEY ("importRowId") REFERENCES "ImportRow"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX IF NOT EXISTS "EmployeeDocument_visibilityLevel_isActive_idx"
  ON "EmployeeDocument"("visibilityLevel", "isActive");
CREATE INDEX IF NOT EXISTS "LeaveRecord_approvalStatus_idx" ON "LeaveRecord"("approvalStatus");
